// Automatically generated by github.com/fardream/gen-gmsk
// enum for MSKbasindtype_enum/Basindtype

package gmsk

import "strconv"

// Basindtype is MSKbasindtype_enum.
//
// Basis identification
type Basindtype uint32

const (
	BI_NEVER       Basindtype = 0 // Never do basis identification.
	BI_ALWAYS      Basindtype = 1 // Basis identification is always performed even if the interior-point optimizer terminates abnormally.
	BI_NO_ERROR    Basindtype = 2 // Basis identification is performed if the interior-point optimizer terminates without an error.
	BI_IF_FEASIBLE Basindtype = 3 // Basis identification is not performed if the interior-point optimizer terminates with a problem status saying that the problem is primal or dual infeasible.
	BI_RESERVERED  Basindtype = 4 // Not currently in use.
)

var _Basindtype_map = map[Basindtype]string{
	BI_NEVER:       "BI_NEVER",
	BI_ALWAYS:      "BI_ALWAYS",
	BI_NO_ERROR:    "BI_NO_ERROR",
	BI_IF_FEASIBLE: "BI_IF_FEASIBLE",
	BI_RESERVERED:  "BI_RESERVERED",
}

func (e Basindtype) String() string {
	if v, ok := _Basindtype_map[e]; ok {
		return v
	}
	return "Basindtype(" + strconv.FormatInt(int64(e), 10) + ")"
}
