// Automatically generated by github.com/fardream/gen-gmsk
// enum for MSKcompresstype_enum/CompressType

package gmsk

// #include <mosek.h>
import "C"

import "strconv"

// CompressType is MSKcompresstype_enum.
//
// Compression types
type CompressType uint32

const (
	COMPRESS_NONE CompressType = C.MSK_COMPRESS_NONE // No compression is used.
	COMPRESS_FREE CompressType = C.MSK_COMPRESS_FREE // The type of compression used is chosen automatically.
	COMPRESS_GZIP CompressType = C.MSK_COMPRESS_GZIP // The type of compression used is gzip compatible.
	COMPRESS_ZSTD CompressType = C.MSK_COMPRESS_ZSTD // The type of compression used is zstd compatible.
)

var _CompressType_map = map[CompressType]string{
	COMPRESS_NONE: "COMPRESS_NONE",
	COMPRESS_FREE: "COMPRESS_FREE",
	COMPRESS_GZIP: "COMPRESS_GZIP",
	COMPRESS_ZSTD: "COMPRESS_ZSTD",
}

func (e CompressType) String() string {
	if v, ok := _CompressType_map[e]; ok {
		return v
	}
	return "CompressType(" + strconv.FormatInt(int64(e), 10) + ")"
}
