// Automatically generated by github.com/fardream/gen-gmsk
// enum for MSKconetype_enum/ConeType

package gmsk

import "strconv"

// ConeType is MSKconetype_enum.
//
// Cone types
type ConeType uint32

const (
	CT_QUAD  ConeType = 0 // The cone is a quadratic cone.
	CT_RQUAD ConeType = 1 // The cone is a rotated quadratic cone.
	CT_PEXP  ConeType = 2 // A primal exponential cone.
	CT_DEXP  ConeType = 3 // A dual exponential cone.
	CT_PPOW  ConeType = 4 // A primal power cone.
	CT_DPOW  ConeType = 5 // A dual power cone.
	CT_ZERO  ConeType = 6 // The zero cone.
)

var _ConeType_map = map[ConeType]string{
	CT_QUAD:  "CT_QUAD",
	CT_RQUAD: "CT_RQUAD",
	CT_PEXP:  "CT_PEXP",
	CT_DEXP:  "CT_DEXP",
	CT_PPOW:  "CT_PPOW",
	CT_DPOW:  "CT_DPOW",
	CT_ZERO:  "CT_ZERO",
}

func (e ConeType) String() string {
	if v, ok := _ConeType_map[e]; ok {
		return v
	}
	return "ConeType(" + strconv.FormatInt(int64(e), 10) + ")"
}
