// Automatically generated by github.com/fardream/gen-gmsk
// enum for MSKconetype_enum/ConeType

package gmsk

// #include <mosek.h>
import "C"

import "strconv"

// ConeType is MSKconetype_enum.
//
// Cone types
type ConeType uint32

const (
	CT_QUAD  ConeType = C.MSK_CT_QUAD  // The cone is a quadratic cone.
	CT_RQUAD ConeType = C.MSK_CT_RQUAD // The cone is a rotated quadratic cone.
	CT_PEXP  ConeType = C.MSK_CT_PEXP  // A primal exponential cone.
	CT_DEXP  ConeType = C.MSK_CT_DEXP  // A dual exponential cone.
	CT_PPOW  ConeType = C.MSK_CT_PPOW  // A primal power cone.
	CT_DPOW  ConeType = C.MSK_CT_DPOW  // A dual power cone.
	CT_ZERO  ConeType = C.MSK_CT_ZERO  // The zero cone.
)

var _ConeType_map = map[ConeType]string{
	CT_QUAD:  "CT_QUAD",
	CT_RQUAD: "CT_RQUAD",
	CT_PEXP:  "CT_PEXP",
	CT_DEXP:  "CT_DEXP",
	CT_PPOW:  "CT_PPOW",
	CT_DPOW:  "CT_DPOW",
	CT_ZERO:  "CT_ZERO",
}

func (e ConeType) String() string {
	if v, ok := _ConeType_map[e]; ok {
		return v
	}
	return "ConeType(" + strconv.FormatInt(int64(e), 10) + ")"
}
