// Automatically generated by github.com/fardream/gen-gmsk
// enum for MSKiomode_enum/IoMode

package gmsk

// #include <mosek.h>
import "C"

import "strconv"

// IoMode is MSKiomode_enum.
//
// Input/output modes
type IoMode uint32

const (
	IOMODE_READ      IoMode = C.MSK_IOMODE_READ      // The file is read-only.
	IOMODE_WRITE     IoMode = C.MSK_IOMODE_WRITE     // The file is write-only. If the file exists then it is truncated when it is opened. Otherwise it is created when it is opened.
	IOMODE_READWRITE IoMode = C.MSK_IOMODE_READWRITE // The file is to read and write.
)

var _IoMode_map = map[IoMode]string{
	IOMODE_READ:      "IOMODE_READ",
	IOMODE_WRITE:     "IOMODE_WRITE",
	IOMODE_READWRITE: "IOMODE_READWRITE",
}

func (e IoMode) String() string {
	if v, ok := _IoMode_map[e]; ok {
		return v
	}
	return "IoMode(" + strconv.FormatInt(int64(e), 10) + ")"
}
