// Automatically generated by github.com/fardream/gen-gmsk
// enum for MSKmiovarseltype_enum/MioVarSelType

package gmsk

// #include <mosek.h>
import "C"

import "strconv"

// MioVarSelType is MSKmiovarseltype_enum.
//
// Mixed-integer variable selection types
type MioVarSelType uint32

const (
	MIO_VAR_SELECTION_FREE       MioVarSelType = C.MSK_MIO_VAR_SELECTION_FREE       // The optimizer decides the variable selection strategy.
	MIO_VAR_SELECTION_PSEUDOCOST MioVarSelType = C.MSK_MIO_VAR_SELECTION_PSEUDOCOST // The optimizer employs pseudocost variable selection.
	MIO_VAR_SELECTION_STRONG     MioVarSelType = C.MSK_MIO_VAR_SELECTION_STRONG     // The optimizer employs strong branching variable selection.
)

var _MioVarSelType_map = map[MioVarSelType]string{
	MIO_VAR_SELECTION_FREE:       "MIO_VAR_SELECTION_FREE",
	MIO_VAR_SELECTION_PSEUDOCOST: "MIO_VAR_SELECTION_PSEUDOCOST",
	MIO_VAR_SELECTION_STRONG:     "MIO_VAR_SELECTION_STRONG",
}

func (e MioVarSelType) String() string {
	if v, ok := _MioVarSelType_map[e]; ok {
		return v
	}
	return "MioVarSelType(" + strconv.FormatInt(int64(e), 10) + ")"
}
