// Automatically generated by github.com/fardream/gen-gmsk
// enum for MSKoptimizertype_enum/OptimizerType

package gmsk

// OptimizerType is MSKoptimizertype_enum.
//
// can be set for the integer parameter [IPAR_OPTIMIZER]
type OptimizerType = int32

const (
	OPTIMIZER_CONIC          OptimizerType = 0 // The optimizer for problems having conic constraints.
	OPTIMIZER_DUAL_SIMPLEX   OptimizerType = 1 // The dual simplex optimizer is used.
	OPTIMIZER_FREE           OptimizerType = 2 // The optimizer is chosen automatically.
	OPTIMIZER_FREE_SIMPLEX   OptimizerType = 3 // One of the simplex optimizers is used.
	OPTIMIZER_INTPNT         OptimizerType = 4 // The interior-point optimizer is used.
	OPTIMIZER_MIXED_INT      OptimizerType = 5 // The mixed-integer optimizer.
	OPTIMIZER_PRIMAL_SIMPLEX OptimizerType = 6 // The primal simplex optimizer is used.
)
