// Automatically generated by github.com/fardream/gen-gmsk
// enum for MSKparametertype_enum/ParameterType

package gmsk

// #include <mosek.h>
import "C"

import "strconv"

// ParameterType is MSKparametertype_enum.
//
// Parameter type
type ParameterType uint32

const (
	PAR_INVALID_TYPE ParameterType = C.MSK_PAR_INVALID_TYPE // Not a valid parameter.
	PAR_DOU_TYPE     ParameterType = C.MSK_PAR_DOU_TYPE     // Is a double parameter.
	PAR_INT_TYPE     ParameterType = C.MSK_PAR_INT_TYPE     // Is an integer parameter.
	PAR_STR_TYPE     ParameterType = C.MSK_PAR_STR_TYPE     // Is a string parameter.
)

var _ParameterType_map = map[ParameterType]string{
	PAR_INVALID_TYPE: "PAR_INVALID_TYPE",
	PAR_DOU_TYPE:     "PAR_DOU_TYPE",
	PAR_INT_TYPE:     "PAR_INT_TYPE",
	PAR_STR_TYPE:     "PAR_STR_TYPE",
}

func (e ParameterType) String() string {
	if v, ok := _ParameterType_map[e]; ok {
		return v
	}
	return "ParameterType(" + strconv.FormatInt(int64(e), 10) + ")"
}
