// Automatically generated by github.com/fardream/gen-gmsk
// enum for MSKsimdegen_enum/Simdegen

package gmsk

import "strconv"

// Simdegen is MSKsimdegen_enum.
//
// Degeneracy strategies
type Simdegen uint32

const (
	SIM_DEGEN_NONE       Simdegen = 0 // The simplex optimizer should use no degeneration strategy.
	SIM_DEGEN_FREE       Simdegen = 1 // The simplex optimizer chooses the degeneration strategy.
	SIM_DEGEN_AGGRESSIVE Simdegen = 2 // The simplex optimizer should use an aggressive degeneration strategy.
	SIM_DEGEN_MODERATE   Simdegen = 3 // The simplex optimizer should use a moderate degeneration strategy.
	SIM_DEGEN_MINIMUM    Simdegen = 4 // The simplex optimizer should use a minimum degeneration strategy.
)

var _Simdegen_map = map[Simdegen]string{
	SIM_DEGEN_NONE:       "SIM_DEGEN_NONE",
	SIM_DEGEN_FREE:       "SIM_DEGEN_FREE",
	SIM_DEGEN_AGGRESSIVE: "SIM_DEGEN_AGGRESSIVE",
	SIM_DEGEN_MODERATE:   "SIM_DEGEN_MODERATE",
	SIM_DEGEN_MINIMUM:    "SIM_DEGEN_MINIMUM",
}

func (e Simdegen) String() string {
	if v, ok := _Simdegen_map[e]; ok {
		return v
	}
	return "Simdegen(" + strconv.FormatInt(int64(e), 10) + ")"
}
