// Automatically generated by github.com/fardream/gen-gmsk
// enum for MSKsimhotstart_enum/Simhotstart

package gmsk

import "strconv"

// Simhotstart is MSKsimhotstart_enum.
//
// Hot-start type employed by the simplex optimizer
type Simhotstart uint32

const (
	SIM_HOTSTART_NONE        Simhotstart = 0 // The simplex optimizer performs a coldstart.
	SIM_HOTSTART_FREE        Simhotstart = 1 // The simplex optimize chooses the hot-start type.
	SIM_HOTSTART_STATUS_KEYS Simhotstart = 2 // Only the status keys of the constraints and variables are used to choose the type of hot-start.
)

var _Simhotstart_map = map[Simhotstart]string{
	SIM_HOTSTART_NONE:        "SIM_HOTSTART_NONE",
	SIM_HOTSTART_FREE:        "SIM_HOTSTART_FREE",
	SIM_HOTSTART_STATUS_KEYS: "SIM_HOTSTART_STATUS_KEYS",
}

func (e Simhotstart) String() string {
	if v, ok := _Simhotstart_map[e]; ok {
		return v
	}
	return "Simhotstart(" + strconv.FormatInt(int64(e), 10) + ")"
}
