// Automatically generated by github.com/fardream/gen-gmsk
// enum for MSKsimprecision_enum/Simprecision

package gmsk

// #include <mosek.h>
import "C"

import "strconv"

// Simprecision is MSKsimprecision_enum.
//
// Experimental. Usage not recommended.
type Simprecision uint32

const (
	SIM_PRECISION_NORMAL   Simprecision = C.MSK_SIM_PRECISION_NORMAL   // Experimental. Usage not recommended.
	SIM_PRECISION_EXTENDED Simprecision = C.MSK_SIM_PRECISION_EXTENDED // Experimental. Usage not recommended.
)

var _Simprecision_map = map[Simprecision]string{
	SIM_PRECISION_NORMAL:   "SIM_PRECISION_NORMAL",
	SIM_PRECISION_EXTENDED: "SIM_PRECISION_EXTENDED",
}

func (e Simprecision) String() string {
	if v, ok := _Simprecision_map[e]; ok {
		return v
	}
	return "Simprecision(" + strconv.FormatInt(int64(e), 10) + ")"
}
