// Automatically generated by github.com/fardream/gen-gmsk
// enum for MSKsimreform_enum/SimReform

package gmsk

// #include <mosek.h>
import "C"

import "strconv"

// SimReform is MSKsimreform_enum.
//
// Problem reformulation.
type SimReform uint32

const (
	SIM_REFORMULATION_OFF        SimReform = C.MSK_SIM_REFORMULATION_OFF        // Disallow the simplex optimizer to reformulate the problem.
	SIM_REFORMULATION_ON         SimReform = C.MSK_SIM_REFORMULATION_ON         // Allow the simplex optimizer to reformulate the problem.
	SIM_REFORMULATION_FREE       SimReform = C.MSK_SIM_REFORMULATION_FREE       // The simplex optimizer can choose freely.
	SIM_REFORMULATION_AGGRESSIVE SimReform = C.MSK_SIM_REFORMULATION_AGGRESSIVE // The simplex optimizer should use an aggressive reformulation strategy.
)

var _SimReform_map = map[SimReform]string{
	SIM_REFORMULATION_OFF:        "SIM_REFORMULATION_OFF",
	SIM_REFORMULATION_ON:         "SIM_REFORMULATION_ON",
	SIM_REFORMULATION_FREE:       "SIM_REFORMULATION_FREE",
	SIM_REFORMULATION_AGGRESSIVE: "SIM_REFORMULATION_AGGRESSIVE",
}

func (e SimReform) String() string {
	if v, ok := _SimReform_map[e]; ok {
		return v
	}
	return "SimReform(" + strconv.FormatInt(int64(e), 10) + ")"
}
