// Automatically generated by github.com/fardream/gen-gmsk
// enum for MSKsolitem_enum/SolItem

package gmsk

import "strconv"

// SolItem is MSKsolitem_enum.
//
// Solution items
type SolItem uint32

const (
	SOL_ITEM_XC  SolItem = 0 // Solution for the constraints.
	SOL_ITEM_XX  SolItem = 1 // Variable solution.
	SOL_ITEM_Y   SolItem = 2 // Lagrange multipliers for equations.
	SOL_ITEM_SLC SolItem = 3 // Lagrange multipliers for lower bounds on the constraints.
	SOL_ITEM_SUC SolItem = 4 // Lagrange multipliers for upper bounds on the constraints.
	SOL_ITEM_SLX SolItem = 5 // Lagrange multipliers for lower bounds on the variables.
	SOL_ITEM_SUX SolItem = 6 // Lagrange multipliers for upper bounds on the variables.
	SOL_ITEM_SNX SolItem = 7 // Lagrange multipliers corresponding to the conic constraints on the variables.
)

var _SolItem_map = map[SolItem]string{
	SOL_ITEM_XC:  "SOL_ITEM_XC",
	SOL_ITEM_XX:  "SOL_ITEM_XX",
	SOL_ITEM_Y:   "SOL_ITEM_Y",
	SOL_ITEM_SLC: "SOL_ITEM_SLC",
	SOL_ITEM_SUC: "SOL_ITEM_SUC",
	SOL_ITEM_SLX: "SOL_ITEM_SLX",
	SOL_ITEM_SUX: "SOL_ITEM_SUX",
	SOL_ITEM_SNX: "SOL_ITEM_SNX",
}

func (e SolItem) String() string {
	if v, ok := _SolItem_map[e]; ok {
		return v
	}
	return "SolItem(" + strconv.FormatInt(int64(e), 10) + ")"
}
