// Automatically generated by github.com/fardream/gen-gmsk
// enum for MSKsoltype_enum/SolType

package gmsk

// #include <mosek.h>
import "C"

import "strconv"

// SolType is MSKsoltype_enum.
//
// Solution types
type SolType uint32

const (
	SOL_ITR SolType = C.MSK_SOL_ITR // The interior solution.
	SOL_BAS SolType = C.MSK_SOL_BAS // The basic solution.
	SOL_ITG SolType = C.MSK_SOL_ITG // The integer solution.
)

var _SolType_map = map[SolType]string{
	SOL_ITR: "SOL_ITR",
	SOL_BAS: "SOL_BAS",
	SOL_ITG: "SOL_ITG",
}

func (e SolType) String() string {
	if v, ok := _SolType_map[e]; ok {
		return v
	}
	return "SolType(" + strconv.FormatInt(int64(e), 10) + ")"
}
