// Automatically generated by github.com/fardream/gen-gmsk
// enum for MSKsymmattype_enum/SymmatType

package gmsk

// #include <mosek.h>
import "C"

import "strconv"

// SymmatType is MSKsymmattype_enum.
//
// Cone types
type SymmatType uint32

const (
	SYMMAT_TYPE_SPARSE SymmatType = C.MSK_SYMMAT_TYPE_SPARSE // Sparse symmetric matrix.
)

var _SymmatType_map = map[SymmatType]string{
	SYMMAT_TYPE_SPARSE: "SYMMAT_TYPE_SPARSE",
}

func (e SymmatType) String() string {
	if v, ok := _SymmatType_map[e]; ok {
		return v
	}
	return "SymmatType(" + strconv.FormatInt(int64(e), 10) + ")"
}
