// Automatically generated by github.com/fardream/gen-gmsk
// function deinitions

package gmsk

// #include <stdlib.h> // for C.free
// #include <mosek.h>
import "C"

import (
	"github.com/fardream/gmsk/res"
)

// GetAccafeidxList is wrapping [MSK_getaccafeidxlist]
//
// [MSK_getaccafeidxlist] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - accidx: MSKint64t
//   - afeidxlist: MSKint64t *
//
// [MSK_getaccafeidxlist]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getaccafeidxlist
func (task *Task) GetAccafeidxList(
	accidx int64,
	afeidxlist *int64,
) res.Code {
	return res.Code(
		C.MSK_getaccafeidxlist(
			task.task,
			C.MSKint64t(accidx),
			(*C.MSKint64t)(afeidxlist),
		),
	)
}

// GetAColSlice is wrapping [MSK_getacolslice]
//
// [MSK_getacolslice] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - first: MSKint32t
//   - last: MSKint32t
//   - maxnumnz: MSKint32t
//   - ptrb: MSKint32t *
//   - ptre: MSKint32t *
//   - sub: MSKint32t *
//   - val: MSKrealt *
//
// [MSK_getacolslice]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getacolslice
func (task *Task) GetAColSlice(
	first int32,
	last int32,
	maxnumnz int32,
	ptrb *int32,
	ptre *int32,
	sub *int32,
	val *float64,
) res.Code {
	return res.Code(
		C.MSK_getacolslice(
			task.task,
			C.MSKint32t(first),
			C.MSKint32t(last),
			C.MSKint32t(maxnumnz),
			(*C.MSKint32t)(ptrb),
			(*C.MSKint32t)(ptre),
			(*C.MSKint32t)(sub),
			(*C.MSKrealt)(val),
		),
	)
}

// GetAfeGSlice is wrapping [MSK_getafegslice]
//
// [MSK_getafegslice] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - first: MSKint64t
//   - last: MSKint64t
//   - g: MSKrealt *
//
// [MSK_getafegslice]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getafegslice
func (task *Task) GetAfeGSlice(
	first int64,
	last int64,
	g *float64,
) res.Code {
	return res.Code(
		C.MSK_getafegslice(
			task.task,
			C.MSKint64t(first),
			C.MSKint64t(last),
			(*C.MSKrealt)(g),
		),
	)
}

// GetARowSlice is wrapping [MSK_getarowslice]
//
// [MSK_getarowslice] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - first: MSKint32t
//   - last: MSKint32t
//   - maxnumnz: MSKint32t
//   - ptrb: MSKint32t *
//   - ptre: MSKint32t *
//   - sub: MSKint32t *
//   - val: MSKrealt *
//
// [MSK_getarowslice]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getarowslice
func (task *Task) GetARowSlice(
	first int32,
	last int32,
	maxnumnz int32,
	ptrb *int32,
	ptre *int32,
	sub *int32,
	val *float64,
) res.Code {
	return res.Code(
		C.MSK_getarowslice(
			task.task,
			C.MSKint32t(first),
			C.MSKint32t(last),
			C.MSKint32t(maxnumnz),
			(*C.MSKint32t)(ptrb),
			(*C.MSKint32t)(ptre),
			(*C.MSKint32t)(sub),
			(*C.MSKrealt)(val),
		),
	)
}

// GetBarsSlice is wrapping [MSK_getbarsslice]
//
// [MSK_getbarsslice] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - whichsol: MSKsoltypee
//   - first: MSKint32t
//   - last: MSKint32t
//   - slicesize: MSKint64t
//   - barsslice: MSKrealt *
//
// [MSK_getbarsslice]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getbarsslice
func (task *Task) GetBarsSlice(
	whichsol SolType,
	first int32,
	last int32,
	slicesize int64,
	barsslice *float64,
) res.Code {
	return res.Code(
		C.MSK_getbarsslice(
			task.task,
			C.MSKsoltypee(whichsol),
			C.MSKint32t(first),
			C.MSKint32t(last),
			C.MSKint64t(slicesize),
			(*C.MSKrealt)(barsslice),
		),
	)
}

// GetBarxSlice is wrapping [MSK_getbarxslice]
//
// [MSK_getbarxslice] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - whichsol: MSKsoltypee
//   - first: MSKint32t
//   - last: MSKint32t
//   - slicesize: MSKint64t
//   - barxslice: MSKrealt *
//
// [MSK_getbarxslice]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getbarxslice
func (task *Task) GetBarxSlice(
	whichsol SolType,
	first int32,
	last int32,
	slicesize int64,
	barxslice *float64,
) res.Code {
	return res.Code(
		C.MSK_getbarxslice(
			task.task,
			C.MSKsoltypee(whichsol),
			C.MSKint32t(first),
			C.MSKint32t(last),
			C.MSKint64t(slicesize),
			(*C.MSKrealt)(barxslice),
		),
	)
}

// GetCList is wrapping [MSK_getclist]
//
// [MSK_getclist] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - num: MSKint32t
//   - subj: const MSKint32t *
//   - c: MSKrealt *
//
// [MSK_getclist]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getclist
func (task *Task) GetCList(
	num int32,
	subj *int32,
	c *float64,
) res.Code {
	return res.Code(
		C.MSK_getclist(
			task.task,
			C.MSKint32t(num),
			(*C.MSKint32t)(subj),
			(*C.MSKrealt)(c),
		),
	)
}

// GetConboundSlice is wrapping [MSK_getconboundslice]
//
// [MSK_getconboundslice] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - first: MSKint32t
//   - last: MSKint32t
//   - bk: MSKboundkeye *
//   - bl: MSKrealt *
//   - bu: MSKrealt *
//
// [MSK_getconboundslice]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getconboundslice
func (task *Task) GetConboundSlice(
	first int32,
	last int32,
	bk *BoundKey,
	bl *float64,
	bu *float64,
) res.Code {
	return res.Code(
		C.MSK_getconboundslice(
			task.task,
			C.MSKint32t(first),
			C.MSKint32t(last),
			(*C.MSKboundkeye)(bk),
			(*C.MSKrealt)(bl),
			(*C.MSKrealt)(bu),
		),
	)
}

// GetCSlice is wrapping [MSK_getcslice]
//
// [MSK_getcslice] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - first: MSKint32t
//   - last: MSKint32t
//   - c: MSKrealt *
//
// [MSK_getcslice]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getcslice
func (task *Task) GetCSlice(
	first int32,
	last int32,
	c *float64,
) res.Code {
	return res.Code(
		C.MSK_getcslice(
			task.task,
			C.MSKint32t(first),
			C.MSKint32t(last),
			(*C.MSKrealt)(c),
		),
	)
}

// GetDjcafeidxList is wrapping [MSK_getdjcafeidxlist]
//
// [MSK_getdjcafeidxlist] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - djcidx: MSKint64t
//   - afeidxlist: MSKint64t *
//
// [MSK_getdjcafeidxlist]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getdjcafeidxlist
func (task *Task) GetDjcafeidxList(
	djcidx int64,
	afeidxlist *int64,
) res.Code {
	return res.Code(
		C.MSK_getdjcafeidxlist(
			task.task,
			C.MSKint64t(djcidx),
			(*C.MSKint64t)(afeidxlist),
		),
	)
}

// GetDjcdomainidxList is wrapping [MSK_getdjcdomainidxlist]
//
// [MSK_getdjcdomainidxlist] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - djcidx: MSKint64t
//   - domidxlist: MSKint64t *
//
// [MSK_getdjcdomainidxlist]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getdjcdomainidxlist
func (task *Task) GetDjcdomainidxList(
	djcidx int64,
	domidxlist *int64,
) res.Code {
	return res.Code(
		C.MSK_getdjcdomainidxlist(
			task.task,
			C.MSKint64t(djcidx),
			(*C.MSKint64t)(domidxlist),
		),
	)
}

// GetDjctermsizeList is wrapping [MSK_getdjctermsizelist]
//
// [MSK_getdjctermsizelist] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - djcidx: MSKint64t
//   - termsizelist: MSKint64t *
//
// [MSK_getdjctermsizelist]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getdjctermsizelist
func (task *Task) GetDjctermsizeList(
	djcidx int64,
	termsizelist *int64,
) res.Code {
	return res.Code(
		C.MSK_getdjctermsizelist(
			task.task,
			C.MSKint64t(djcidx),
			(*C.MSKint64t)(termsizelist),
		),
	)
}

// GetSkcSlice is wrapping [MSK_getskcslice]
//
// [MSK_getskcslice] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - whichsol: MSKsoltypee
//   - first: MSKint32t
//   - last: MSKint32t
//   - skc: MSKstakeye *
//
// [MSK_getskcslice]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getskcslice
func (task *Task) GetSkcSlice(
	whichsol SolType,
	first int32,
	last int32,
	skc *StaKey,
) res.Code {
	return res.Code(
		C.MSK_getskcslice(
			task.task,
			C.MSKsoltypee(whichsol),
			C.MSKint32t(first),
			C.MSKint32t(last),
			(*C.MSKstakeye)(skc),
		),
	)
}

// GetSkxSlice is wrapping [MSK_getskxslice]
//
// [MSK_getskxslice] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - whichsol: MSKsoltypee
//   - first: MSKint32t
//   - last: MSKint32t
//   - skx: MSKstakeye *
//
// [MSK_getskxslice]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getskxslice
func (task *Task) GetSkxSlice(
	whichsol SolType,
	first int32,
	last int32,
	skx *StaKey,
) res.Code {
	return res.Code(
		C.MSK_getskxslice(
			task.task,
			C.MSKsoltypee(whichsol),
			C.MSKint32t(first),
			C.MSKint32t(last),
			(*C.MSKstakeye)(skx),
		),
	)
}

// GetSlcSlice is wrapping [MSK_getslcslice]
//
// [MSK_getslcslice] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - whichsol: MSKsoltypee
//   - first: MSKint32t
//   - last: MSKint32t
//   - slc: MSKrealt *
//
// [MSK_getslcslice]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getslcslice
func (task *Task) GetSlcSlice(
	whichsol SolType,
	first int32,
	last int32,
	slc *float64,
) res.Code {
	return res.Code(
		C.MSK_getslcslice(
			task.task,
			C.MSKsoltypee(whichsol),
			C.MSKint32t(first),
			C.MSKint32t(last),
			(*C.MSKrealt)(slc),
		),
	)
}

// GetSlxSlice is wrapping [MSK_getslxslice]
//
// [MSK_getslxslice] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - whichsol: MSKsoltypee
//   - first: MSKint32t
//   - last: MSKint32t
//   - slx: MSKrealt *
//
// [MSK_getslxslice]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getslxslice
func (task *Task) GetSlxSlice(
	whichsol SolType,
	first int32,
	last int32,
	slx *float64,
) res.Code {
	return res.Code(
		C.MSK_getslxslice(
			task.task,
			C.MSKsoltypee(whichsol),
			C.MSKint32t(first),
			C.MSKint32t(last),
			(*C.MSKrealt)(slx),
		),
	)
}

// GetSnxSlice is wrapping [MSK_getsnxslice]
//
// [MSK_getsnxslice] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - whichsol: MSKsoltypee
//   - first: MSKint32t
//   - last: MSKint32t
//   - snx: MSKrealt *
//
// [MSK_getsnxslice]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getsnxslice
func (task *Task) GetSnxSlice(
	whichsol SolType,
	first int32,
	last int32,
	snx *float64,
) res.Code {
	return res.Code(
		C.MSK_getsnxslice(
			task.task,
			C.MSKsoltypee(whichsol),
			C.MSKint32t(first),
			C.MSKint32t(last),
			(*C.MSKrealt)(snx),
		),
	)
}

// GetSolutionSlice is wrapping [MSK_getsolutionslice]
//
// [MSK_getsolutionslice] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - whichsol: MSKsoltypee
//   - solitem: MSKsoliteme
//   - first: MSKint32t
//   - last: MSKint32t
//   - values: MSKrealt *
//
// [MSK_getsolutionslice]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getsolutionslice
func (task *Task) GetSolutionSlice(
	whichsol SolType,
	solitem SolItem,
	first int32,
	last int32,
	values *float64,
) res.Code {
	return res.Code(
		C.MSK_getsolutionslice(
			task.task,
			C.MSKsoltypee(whichsol),
			C.MSKsoliteme(solitem),
			C.MSKint32t(first),
			C.MSKint32t(last),
			(*C.MSKrealt)(values),
		),
	)
}

// GetSucSlice is wrapping [MSK_getsucslice]
//
// [MSK_getsucslice] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - whichsol: MSKsoltypee
//   - first: MSKint32t
//   - last: MSKint32t
//   - suc: MSKrealt *
//
// [MSK_getsucslice]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getsucslice
func (task *Task) GetSucSlice(
	whichsol SolType,
	first int32,
	last int32,
	suc *float64,
) res.Code {
	return res.Code(
		C.MSK_getsucslice(
			task.task,
			C.MSKsoltypee(whichsol),
			C.MSKint32t(first),
			C.MSKint32t(last),
			(*C.MSKrealt)(suc),
		),
	)
}

// GetSuxSlice is wrapping [MSK_getsuxslice]
//
// [MSK_getsuxslice] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - whichsol: MSKsoltypee
//   - first: MSKint32t
//   - last: MSKint32t
//   - sux: MSKrealt *
//
// [MSK_getsuxslice]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getsuxslice
func (task *Task) GetSuxSlice(
	whichsol SolType,
	first int32,
	last int32,
	sux *float64,
) res.Code {
	return res.Code(
		C.MSK_getsuxslice(
			task.task,
			C.MSKsoltypee(whichsol),
			C.MSKint32t(first),
			C.MSKint32t(last),
			(*C.MSKrealt)(sux),
		),
	)
}

// GetVarboundSlice is wrapping [MSK_getvarboundslice]
//
// [MSK_getvarboundslice] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - first: MSKint32t
//   - last: MSKint32t
//   - bk: MSKboundkeye *
//   - bl: MSKrealt *
//   - bu: MSKrealt *
//
// [MSK_getvarboundslice]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getvarboundslice
func (task *Task) GetVarboundSlice(
	first int32,
	last int32,
	bk *BoundKey,
	bl *float64,
	bu *float64,
) res.Code {
	return res.Code(
		C.MSK_getvarboundslice(
			task.task,
			C.MSKint32t(first),
			C.MSKint32t(last),
			(*C.MSKboundkeye)(bk),
			(*C.MSKrealt)(bl),
			(*C.MSKrealt)(bu),
		),
	)
}

// GetVarTypeList is wrapping [MSK_getvartypelist]
//
// [MSK_getvartypelist] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - num: MSKint32t
//   - subj: const MSKint32t *
//   - vartype: MSKvariabletypee *
//
// [MSK_getvartypelist]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getvartypelist
func (task *Task) GetVarTypeList(
	num int32,
	subj *int32,
	vartype *VariableType,
) res.Code {
	return res.Code(
		C.MSK_getvartypelist(
			task.task,
			C.MSKint32t(num),
			(*C.MSKint32t)(subj),
			(*C.MSKvariabletypee)(vartype),
		),
	)
}

// GetXcSlice is wrapping [MSK_getxcslice]
//
// [MSK_getxcslice] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - whichsol: MSKsoltypee
//   - first: MSKint32t
//   - last: MSKint32t
//   - xc: MSKrealt *
//
// [MSK_getxcslice]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getxcslice
func (task *Task) GetXcSlice(
	whichsol SolType,
	first int32,
	last int32,
	xc *float64,
) res.Code {
	return res.Code(
		C.MSK_getxcslice(
			task.task,
			C.MSKsoltypee(whichsol),
			C.MSKint32t(first),
			C.MSKint32t(last),
			(*C.MSKrealt)(xc),
		),
	)
}

// GetYSlice is wrapping [MSK_getyslice]
//
// [MSK_getyslice] returns MSKrescodee and has following parameters
//   - task: MSKtask_t
//   - whichsol: MSKsoltypee
//   - first: MSKint32t
//   - last: MSKint32t
//   - y: MSKrealt *
//
// [MSK_getyslice]: https://docs.mosek.com/latest/capi/alphabetic-functionalities.html#mosek.task.getyslice
func (task *Task) GetYSlice(
	whichsol SolType,
	first int32,
	last int32,
	y *float64,
) res.Code {
	return res.Code(
		C.MSK_getyslice(
			task.task,
			C.MSKsoltypee(whichsol),
			C.MSKint32t(first),
			C.MSKint32t(last),
			(*C.MSKrealt)(y),
		),
	)
}
