// Automatically generated by github.com/fardream/gen-gmsk
// enum for MSKvariabletype_enum/VariableType

package gmsk

import "strconv"

// VariableType is MSKvariabletype_enum.
//
// Variable types
type VariableType uint32

const (
	VAR_TYPE_CONT VariableType = 0 // Is a continuous variable.
	VAR_TYPE_INT  VariableType = 1 // Is an integer variable.
)

var _VariableType_map = map[VariableType]string{
	VAR_TYPE_CONT: "VAR_TYPE_CONT",
	VAR_TYPE_INT:  "VAR_TYPE_INT",
}

func (e VariableType) String() string {
	if v, ok := _VariableType_map[e]; ok {
		return v
	}
	return "VariableType(" + strconv.FormatInt(int64(e), 10) + ")"
}
